### ISSUE TITLE
Module commands from admin server view error out

### ISSUE THREAD

**Issue by scop** [UpCloudLtd/upcloud-whmcs-module#51]
Module commands (at least Start VPS, Stop VPS, Reboot VPS, Suspend, Unsuspend) do not work but result in 500 internal server errors.

The error trace below is for Start VPS, but the trace points to vmManager's create for some reason.

```
NOTICE: PHP message: [WHMCS Application] ERROR: ParseError: syntax error, unexpected variable "$message" in /var/www/html/modules/servers/upCloudVps/lib/vmManager.php:105 Stack trace: #0 /var/www/html/modules/servers/upCloudVps/upCloudVps.php(130): WHMCS\Module\Autoloader->moduleClassLoader('WHMCS\\Module\\Se...') #1 [internal function]: upCloudVps_StartVPS(Array) #2 /var/www/html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('upCloudVps_Star...', Array) #3 /var/www/html/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call('StartVPS', Array) #4 /var/www/html/includes/modulefunctions.php(0): WHMCS\Module\Server->call('StartVPS', Array) #5 /var/www/html/admin/clientsservices.php(0): ServerCustomFunction(12, 'StartVPS', 0, Array) #6 {main} {"exception":"[object] (ParseError(code: 0): syntax error, unexpected variable \"$message\" at /var/www/html/modules/servers/upCloudVps/lib/vmManager.php:105)"} []
```

**Comment by adityawbwce** [comment]
Not able to reproduce it with stop VPS command and it works as you can see in the module log

![image](https://github.com/user-attachments/assets/530cd16f-ceb7-4bdf-a8c6-820a44efd2c7)

![image](https://github.com/user-attachments/assets/742bb47e-d457-41f9-82b8-0b9d9dd237be)

No problem with Start VPS Command it works for me as you can see below:

![image](https://github.com/user-attachments/assets/2c79e6b1-41d0-451c-847b-7f4ba7827351)

**Comment by scop** [comment]
I have found that these work if the product type is set to Server/VPS. However in an instructions PDF I have, there is a recommendation to use Other as the product type:

> Product Type – Select as Other, we recommended to select type as Other, because during order process your customer will not prompted to provide Hostname, Password, NS1 & NS2 prefix. If Sever/VPS selected then your customer will be prompted to provide these details.

If the product type is set to Other, then this error does occur.

**Comment by thevilledev** [comment]
We'll add the product type which works to readme so that it's not blocking the release. Other type to be fixed right after.
